# Documentation for TourPress WordPress theme.
#
# Author: Fahid Javid
#
# MKDOCS http://www.mkdocs.org/
# mkdocs-material http://squidfunk.github.io/mkdocs-material/
# License: The MIT License (MIT)

# Branding
site_name: TourPress Documentation
site_description: 'Documentation for TourPress WordPress theme.'
site_author: 'Inspiry Themes'
site_url: 'https://inspirythemes.github.io/tp-doc/'

# Repository
repo_name: 'GitHub'
repo_url: 'https://github.com/InspiryThemes/tp-doc'

# Copyright
copyright: 'Copyright &copy; 2018 InspiryThemes'

theme:
  language: 'en'
  name: 'material'
  palette:
    primary: 'light-blue'
    accent: 'green'
  font:
    text: 'Open Sans'
    code: 'Ubuntu Mono'
  theme_dir: 'mkdocs-material/material'


extra:
  version: 1.0
  social:
      - type: 'twitter'
        link: 'https://twitter.com/inspirythemes'
      - type: 'facebook'
        link: 'https://www.facebook.com/InspiryThemes/'


extra_css:
  - 'stylesheets/style.css'

nav:
    - Introduction: index.md
    - Installation: installation.md
    - Import Demo Contents: import-demo-contents.md
    - Home Page:
      - Creating and Configuring Page: home/create-page.md
      - Home Page Settings:
        - Sections Manager: home/settings/sections-manager.md
        - Slider Area: home/settings/slider-area.md
        - Features: home/settings/features.md
        - Featured Packages: home/settings/featured-packages.md
        - Travel Destinations: home/settings/popular-destinations.md
        - Special Offers: home/settings/special-offers.md
        - Destination By Mood: home/settings/destination-by-mood.md
        - Blog Posts: home/settings/recent-from-blog.md
        - Testimonials: home/settings/testimonials.md
        - Explore Tours: home/settings/explore-tours.md
    - Header:
      - Topbar Settings: header/topbar.md
      - Banner Settings: header/banner.md
      - Other Settings: header/others.md
    - Footer: footer/footer-settings.md
    - Tours Search: tours-search.md
    - Tours & Tours Page:
      - Add New Tour: tour/add-tour.md
      - Create Tours Page: tour/create-tours-page.md 
    - Tour Detils Page: tour/settings/tour-detail-page.md
    - Taxonomy & Archive Pages: tour/taxonomy-and-archive-pages.md
    - Other Pages: 
      - Gallery Page: gallery-page.md
      - Blog/News Page: pages.md
      - Contact Page: contact-page.md
      - FAQs Page: faqs-page.md
    - Other Posts: 
      - Add Post: posts.md
      - Add Testimonial: testimonials.md
    - Widgets:
      - Recent Posts: widgets/recent-posts.md
      - Top Rated Tours: widgets/top-rated-tours.md
      - Address & Cotacts: widgets/address-contact.md
      - Social Share: widgets/soical-share.md
      - Tours Widget: widgets/tours.md
      - Tours Search: widgets/tours-search.md
    - Price Format Settings: tour/settings/price-format.md
    - URL Slugs Settings: tour/settings/tour-slugs.md
    - Google Maps API: tour/settings/tour-google-map-api.md
    - WooCommerce Setup: woocommerce.md
    - Customization: customization.md

# Change it to true before building (mkdocs build) for putting online.
# It should be false for themeforest package.
use_directory_urls: true

markdown_extensions:
  - admonition
  - codehilite
  - toc
  - footnotes
  - pymdownx.arithmatex
  - pymdownx.betterem
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
     emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
  - meta